import { useEffect } from 'react'
import Layout from '../components/Layout.jsx'
import { Button, Eyebrow } from '../components/ui.jsx'

// Files live in public/brand/, generated by scripts/brand/build.py.
const ASSETS = [
  {
    file: 'crosspoint-logo-light',
    name: 'Logo',
    note: 'Icon + wordmark, for light backgrounds.',
    bg: 'bg-white',
    wide: true,
  },
  {
    file: 'crosspoint-logo-dark',
    name: 'Logo, dark',
    note: 'Icon + wordmark, for dark backgrounds.',
    bg: 'bg-stone-900',
    wide: true,
  },
  { file: 'crosspoint-icon', name: 'App icon', note: 'Works on any background.', bg: 'bg-stone-100' },
  { file: 'crosspoint-mark-black', name: 'Mark, black', note: 'For light backgrounds.', bg: 'bg-white' },
  { file: 'crosspoint-mark-white', name: 'Mark, white', note: 'For dark backgrounds.', bg: 'bg-stone-900' },
]

const COLORS = [
  { name: 'Reader Green', hex: '#3d6652', swatch: 'bg-brand-600' },
  { name: 'Sage', hex: '#8fb9a6', swatch: 'bg-brand-300' },
  { name: 'Ink', hex: '#1c1917', swatch: 'bg-stone-900' },
  { name: 'Paper', hex: '#fafaf9', swatch: 'bg-stone-50' },
]

export default function BrandPage() {
  useEffect(() => {
    document.title = 'Brand Kit - CrossPoint Reader'
  }, [])

  return (
    <Layout>
      <div className="mx-auto max-w-7xl px-6 py-16 sm:py-24 lg:px-8">
        <div className="max-w-2xl">
          <Eyebrow>Press &amp; partners</Eyebrow>
          <h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-stone-900 sm:text-4xl">
            Brand kit
          </h1>
          <p className="mt-3 text-base/7 text-stone-600">
            Logos for articles, videos, and partner pages. Use SVG where you can, PNG where you
            can't. Please don't recolor, stretch, or redraw the mark.
          </p>
        </div>

        <ul role="list" className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {ASSETS.map((a) => (
            <li
              key={a.file}
              className={`overflow-hidden rounded-xl bg-white ring-1 ring-stone-950/10 ${a.wide ? 'sm:col-span-2 lg:col-span-3' : ''}`}
            >
              <div className={`flex h-48 items-center justify-center p-8 ${a.bg} ${a.wide ? 'sm:h-56' : ''}`}>
                <img
                  src={`/brand/${a.file}.svg`}
                  alt={`CrossPoint Reader ${a.name.toLowerCase()}`}
                  className={a.wide ? 'h-auto max-h-24 w-full max-w-xl object-contain' : 'h-full w-auto'}
                />
              </div>
              <div className="flex flex-wrap items-center justify-between gap-4 border-t border-stone-200 p-4">
                <div>
                  <p className="text-sm font-semibold text-stone-900">{a.name}</p>
                  <p className="text-sm text-stone-500">{a.note}</p>
                </div>
                <div className="flex gap-2">
                  <Button href={`/brand/${a.file}.svg`} download>
                    SVG
                  </Button>
                  <Button href={`/brand/${a.file}.png`} download>
                    PNG
                  </Button>
                </div>
              </div>
            </li>
          ))}
        </ul>

        <div className="mt-16 grid gap-12 lg:grid-cols-2">
          <div>
            <h2 className="font-display text-xl font-semibold text-stone-900">Colors</h2>
            <ul role="list" className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">
              {COLORS.map((c) => (
                <li key={c.hex}>
                  <div className={`h-16 rounded-lg ring-1 ring-stone-950/10 ${c.swatch}`} />
                  <p className="mt-2 text-sm font-medium text-stone-900">{c.name}</p>
                  <p className="font-mono text-xs text-stone-500 select-all">{c.hex}</p>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <h2 className="font-display text-xl font-semibold text-stone-900">Type</h2>
            <p className="mt-4 text-sm/6 text-stone-600">
              The wordmark and headlines are set in{' '}
              <a href="https://fonts.google.com/specimen/Lora" className="font-medium text-brand-600 hover:text-brand-700">
                Lora
              </a>{' '}
              SemiBold. Body text uses{' '}
              <a href="https://rsms.me/inter/" className="font-medium text-brand-600 hover:text-brand-700">
                Inter
              </a>
              . Write the name as <span className="font-medium text-stone-900">CrossPoint Reader</span>, or{' '}
              <span className="font-medium text-stone-900">CrossPoint</span> for short.
            </p>
          </div>
        </div>
      </div>
    </Layout>
  )
}
